# Generated by Django 2.2.2 on 2019-08-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=80)),
                ('credit_hours', models.PositiveIntegerField(default=3)),
            ],
            options={
                'ordering': ['subject', 'number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_code', models.CharField(max_length=6)),
                ('semester_fraction', models.IntegerField(choices=[(0, 'Full Semester'), (1, 'First Half Semester'), (2, 'Second Half Semester')], default=0)),
                ('max_enrollment', models.PositiveIntegerField(default=10)),
                ('banner_comment', models.CharField(blank=True, help_text='(optional)', max_length=20, null=True)),
                ('crn', models.CharField(max_length=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='banner.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pidm', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('formal_first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abbrev', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['abbrev'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=0)),
                ('begin_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='banner.CourseOffering')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferingInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_instructors', to='banner.CourseOffering')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_instructors', to='banner.FacultyMember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='instructor',
            field=models.ManyToManyField(blank=True, related_name='course_offerings', through='banner.OfferingInstructor', to='banner.FacultyMember'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='banner.Subject'),
        ),
    ]
