# Generated by Django 2.2.2 on 2019-09-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='ichair_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
