# Generated by Django 2.2.2 on 2020-01-11 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20190907_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOfferingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=60)),
                ('sequence_number', models.DecimalField(decimal_places=20, max_digits=23)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_comments', to='banner.CourseOffering')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
