# Generated by Django 2.2.2 on 2020-01-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_courseofferingcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseofferingcomment',
            options={'ordering': ['sequence_number']},
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='banner_comment',
        ),
    ]
