# Generated by Django 2.2.2 on 2020-02-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_auto_20200111_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCodesToImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_code', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ['term_code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectToImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abbrev', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['abbrev'],
            },
        ),
    ]
