# Generated by Django 2.2.2 on 2020-02-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_semestercodestoimport_subjecttoimport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemesterCodesToImport',
            new_name='SemesterCodeToImport',
        ),
    ]
