# Generated by Django 2.2.2 on 2020-08-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_auto_20200822_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercodetoimport',
            name='allow_room_copy',
            field=models.BooleanField(default=True),
        ),
    ]
