# Generated by Django 2.2.2 on 2021-01-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0010_auto_20201212_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercodetoimport',
            name='allow_room_requests',
            field=models.BooleanField(default=False),
        ),
    ]
