# Generated by Django 2.2.2 on 2021-01-15 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0011_semestercodetoimport_allow_room_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestercodetoimport',
            name='allow_room_copy',
        ),
    ]
