# Generated by Django 3.2.4 on 2021-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0012_remove_semestercodetoimport_allow_room_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='scheduled_class_objects', to='banner.Room'),
        ),
    ]
