# Generated by Django 3.2.4 on 2021-06-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0014_auto_20210614_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledclass',
            name='room',
        ),
    ]
