# Generated by Django 3.2.4 on 2021-06-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0015_remove_scheduledclass_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='campus',
            field=models.CharField(choices=[('U', 'U'), ('OCP', 'OCP'), ('OCD', 'OCD')], default='U', max_length=3),
        ),
    ]
