# Generated by Django 3.2.4 on 2021-08-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0016_courseoffering_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
