# Generated by Django 3.2.4 on 2021-08-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0017_room_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
        migrations.AddField(
            model_name='room',
            name='inactive_after',
            field=models.DateField(blank=True, null=True),
        ),
    ]
