# Generated by Django 3.2.13 on 2022-06-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0018_auto_20210823_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='campus',
            field=models.CharField(choices=[('U', 'U'), ('OCP', 'OCP'), ('OCD', 'OCD'), ('ECC', 'ECC')], default='U', max_length=3),
        ),
    ]
