# Generated by Django 3.2.14 on 2023-08-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0019_alter_courseoffering_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='external_system_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
