# Generated by Django 2.2.2 on 2019-06-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_facultymember_inactive_starting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherloadtype',
            options={'ordering': ['load_type']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='crn',
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule_semester',
            field=models.ManyToManyField(blank=True, help_text='Semester(s) offered', to='planner.SemesterName'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule_year',
            field=models.CharField(choices=[('E', 'Even'), ('O', 'Odd'), ('B', 'Both')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='comment',
            field=models.CharField(blank=True, help_text='(optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='degreeprogram',
            name='entering_year',
            field=models.CharField(choices=[('E', 'Even'), ('O', 'Odd'), ('B', 'Both')], max_length=1),
        ),
        migrations.AlterField(
            model_name='degreeprogram',
            name='name',
            field=models.CharField(help_text='e.g., Physics BS, entering odd years', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='rank',
            field=models.CharField(choices=[('Inst', 'Instructor'), ('Adj', 'Adjunct Professor'), ('Asst', 'Assistant Professor'), ('Assoc', 'Associate Professor'), ('Full', 'Professor')], max_length=8),
        ),
        migrations.AlterField(
            model_name='note',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='planner.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='otherload',
            name='comments',
            field=models.CharField(blank=True, help_text='optional longer comments', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otherloadtype',
            name='load_type',
            field=models.CharField(help_text='e.g., Research, Chair, Sabbatical', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='display_name',
            field=models.CharField(help_text='e.g., Technical Electives, or Literature;this is the title that will show up when studentsdo a graduation audit.', max_length=50),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='name',
            field=models.CharField(help_text='e.g., PhysicsBS Technical Electives, or GenEd Literature;first part is helpful for searching (when creating a major).', max_length=50),
        ),
        migrations.AlterField(
            model_name='requirementblock',
            name='courses',
            field=models.ManyToManyField(help_text='Select courses for this requirement.', to='planner.Course'),
        ),
        migrations.AlterField(
            model_name='requirementblock',
            name='display_name',
            field=models.CharField(help_text='e.g., Technical Electives, or Literature;this is the title that will show up when studentsdo a graduation audit.', max_length=50),
        ),
        migrations.AlterField(
            model_name='requirementblock',
            name='list_order',
            field=models.PositiveIntegerField(default=1, help_text='Preferred place in the listof requirements; it is OK if numbersare repeated or skipped.'),
        ),
        migrations.AlterField(
            model_name='requirementblock',
            name='name',
            field=models.CharField(help_text='e.g., PhysicsBS Technical Electives, or GenEd Literature;first part is helpful for searching (when creating a major).', max_length=50),
        ),
        migrations.AlterField(
            model_name='requirementblock',
            name='requirement_type',
            field=models.IntegerField(choices=[(1, 'AND'), (2, 'OR')], default=1, help_text='Choose AND if all are required,OR if a subset is required.'),
        ),
        migrations.AlterField(
            model_name='requirementblock',
            name='text_for_user',
            field=models.CharField(blank=True, help_text='Optional helpful text for the user;will appear in the graduation audit.', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduledclass',
            name='comment',
            field=models.CharField(blank=True, help_text='optional brief comment', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledclass',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='catalog_year',
            field=models.ForeignKey(help_text='Catalog year for graduation plan', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planner.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entering_year',
            field=models.ForeignKey(help_text='Year student entered university', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planner.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='permission_level',
            field=models.IntegerField(choices=[(0, 'view only'), (1, 'department scheduler'), (2, 'super-user')], default=0),
        ),
    ]
