# Generated by Django 2.2.2 on 2019-07-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20190628_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='e.g., 10435', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='banner_code',
            field=models.CharField(blank=True, help_text='e.g., 201990', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='crn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offerings', to='planner.CRN'),
        ),
    ]
