# Generated by Django 2.2.2 on 2019-07-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20190701_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='semester_fraction',
            field=models.IntegerField(choices=[(0, 'Full Semester'), (1, 'First Half Semester'), (2, 'Second Half Semester')], default=0),
        ),
    ]
