# Generated by Django 2.2.2 on 2019-07-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_courseoffering_semester_fraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymember',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
