# Generated by Django 2.2.2 on 2019-07-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20190711_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='crn',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='CRN',
        ),
    ]
