# Generated by Django 2.2.2 on 2019-07-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20190712_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultymember',
            old_name='faculty_id',
            new_name='pidm',
        ),
    ]
