# Generated by Django 2.2.2 on 2019-07-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20190712_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='trusted_departments',
            field=models.ManyToManyField(blank=True, related_name='trusting_departments', to='planner.Department'),
        ),
    ]
