# Generated by Django 2.2.2 on 2019-07-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_department_trusted_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledclass',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='planner.Room'),
        ),
    ]
