# Generated by Django 2.2.2 on 2019-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20190722_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='trusted_departments',
            field=models.ManyToManyField(blank=True, related_name='subject_trusting_departments', to='planner.Department'),
        ),
    ]
