# Generated by Django 2.2.2 on 2019-09-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_auto_20190905_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offeringinstructor',
            options={'ordering': ['instructor__last_name', 'instructor__first_name']},
        ),
        migrations.CreateModel(
            name='DeltaCourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crn', models.CharField(blank=True, max_length=5, null=True)),
                ('extra_comment', models.CharField(blank=True, help_text='(optional comment for the registrar)', max_length=200, null=True)),
                ('requested_action', models.IntegerField(choices=[(0, 'Create'), (1, 'Update'), (2, 'Delete')], default=1)),
                ('update_meeting_times', models.BooleanField(default=False)),
                ('update_instructors', models.BooleanField(default=False)),
                ('update_semester_fraction', models.BooleanField(default=False)),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delta_offerings', to='planner.CourseOffering')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delta_offerings', to='planner.Semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
