# Generated by Django 2.2.2 on 2019-09-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_auto_20190907_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='deltacourseoffering',
            name='update_max_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
