# Generated by Django 2.2.2 on 2019-09-24 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_deltacourseoffering_update_max_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='banner_title',
        ),
        migrations.CreateModel(
            name='BannerTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_titles', to='planner.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
