# Generated by Django 2.2.2 on 2020-01-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_deltacourseoffering_update_public_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltacourseoffering',
            name='extra_comment',
            field=models.CharField(blank=True, help_text='(optional comment for the registrar)', max_length=500, null=True),
        ),
    ]
