# Generated by Django 2.2.2 on 2020-07-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_auto_20200129_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeringinstructor',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.IntegerField(choices=[(0, 'Warning'), (1, 'Information'), (3, 'Error')], default=0)),
                ('note', models.TextField()),
                ('dismissed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='planner.Department')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='planner.AcademicYear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
