# Generated by Django 2.2.2 on 2020-07-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_auto_20200729_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indentation_level', models.IntegerField(choices=[(0, 'Top-level'), (1, 'Single-tabbed'), (2, 'Double-tabbed')], default=0)),
                ('fragment', models.TextField()),
                ('sequence_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='note',
        ),
        migrations.AddField(
            model_name='message',
            name='fragments',
            field=models.ManyToManyField(blank=True, related_name='messages', to='planner.MessageFragment'),
        ),
    ]
