# Generated by Django 2.2.2 on 2020-07-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_auto_20200729_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagefragment',
            options={'ordering': ['sequence_number']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='fragments',
        ),
        migrations.AddField(
            model_name='messagefragment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='planner.Message'),
        ),
    ]
