# Generated by Django 2.2.2 on 2020-07-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0025_auto_20200729_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='planner.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='messagefragment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='planner.Message'),
        ),
    ]
