# Generated by Django 2.2.2 on 2020-07-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_auto_20200729_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefragment',
            name='indentation_level',
            field=models.IntegerField(choices=[(0, 'Top-level'), (1, 'Single-tabbed'), (2, 'Double-tabbed'), (3, 'Triple-tabbed')], default=0),
        ),
    ]
