# Generated by Django 2.2.2 on 2020-12-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0028_auto_20201212_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='deltacourseoffering',
            name='update_delivery_method',
            field=models.BooleanField(default=False),
        ),
    ]
