# Generated by Django 3.2.4 on 2021-06-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0029_deltacourseoffering_update_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='scheduled_class_objects', to='planner.Room'),
        ),
    ]
