# Generated by Django 3.2.4 on 2021-06-14 19:41
# manual edits by KK
# https://ponytech.net/blog/convert-foreign-key-many-to-many-using-django-migrations

from django.db import models, migrations

def forward(apps, schema_editor):
    ScheduledClass = apps.get_model("planner", "ScheduledClass")
    for scheduled_class in ScheduledClass.objects.all():
        # copy the room information (formerly a foreign key) to the new many-to-many rooms property....
        if scheduled_class.room is not None:
            scheduled_class.rooms.add(scheduled_class.room)

class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0030_scheduledclass_rooms'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]