# Generated by Django 3.2.13 on 2022-06-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0033_room_inactive_after'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledclass',
            options={'ordering': ['begin_at']},
        ),
    ]
