# Generated by Django 3.2.13 on 2022-07-06 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0035_auto_20220621_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='years', to='planner.department'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
