# Generated by Django 3.2.14 on 2022-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0037_department_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_marked_as_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
