# Generated by Django 3.2.14 on 2023-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0038_academicyear_is_marked_as_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='external_system_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
